name: Build SmartTube for Android TV

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 14 (Zulu)
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 14

    - name: Grant execute permission
      run: chmod +x ./gradlew

    - name: Clean & build TV release APK
      run: ./gradlew clean assembleStorigRelease

    - name: Upload release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartTube-AndroidTV-Release-APK
        path: app/build/outputs/apk/storig/release/*.apk
